//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int Id_toy { get; set; }
        public int Id_purchase { get; set; }
        public int Id_user { get; set; }
        public Nullable<int> Amount_of_toys { get; set; }
        public Nullable<int> Cost { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual Toy Toy { get; set; }
        public virtual User User { get; set; }
    }
}
