//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToyShop.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies_on_warehouse
    {
        public int Id_warehouse { get; set; }
        public int Id_supply { get; set; }
        public int Amount_of_toys_in_supply { get; set; }
    
        public virtual Supply Supply { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
